<?php

/**
 * @file
 * Drupal Auth for simpleSAMLphp install/update/schema hook implementations.
 */

declare(strict_types = 1);

/**
 * Implements hook_update_N;
 */
function drupalauth4ssp_update_8001() {
  // Clear the unused "authsource" configuration option, if necessary.
  $configFactory = \Drupal::configFactory();
  $configuration = $configFactory->getEditable('drupalauth4ssp.settings');
  if (!empty($configuration)) {
    $configuration->clear('authsource');
  }
}
