<?php

/**
 * @file
 * Drupal Auth for simpleSAMLphp hook implementation.
 */

declare(strict_types = 1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function drupalauth4ssp_form_user_login_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  // Add submit handler to change form redirect URL.
  $form['#submit'][] = 'drupalauth4ssp_user_login_submit';
}

/**
 * Ensures redirect set to home page upon successful login.
 *
 * For the reasons for this,
 * @see \Drupal\drupalauth4ssp\EventSubscriber\LoginRouteRequestSubscriber.
 *
 * @param array $form
 *   Form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Form state.
 */
function drupalauth4ssp_user_login_submit($form, FormStateInterface $form_state) {
  // Send the user to the front page.
  $form_state->setRedirectUrl(Url::fromRoute('<front>')->setAbsolute());
}

// @todo Need to bring back the validation code for SSO-enabled users (bring in
// from drupalauth4ssp_extra_features module).
