drupalauth4ssp.settings:
  type: config_object
  label: DrupalAuth for SimpleSamlPHP settings
  mapping:
    is_possible_idp_session_cookie_name:
      type: string
      label: 'Name of "possible IdP session" cookie'
